# deployment/helm/workflow-system/values.yaml
global:
  environment: production
  domain: workflow.example.com

backend:
  name: wms-backend
  replicaCount: 3
  image:
    repository: ${ECR_REGISTRY}/wms-backend
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

frontend:
  name: wms-frontend
  replicaCount: 2
  image:
    repository: ${ECR_REGISTRY}/wms-frontend
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

mongodb:
  enabled: true
  auth:
    rootPassword: ${MONGODB_ROOT_PASSWORD}
    username: ${MONGODB_USERNAME}
    password: ${MONGODB_PASSWORD}
  persistence:
    enabled: true
    size: 10Gi

redis:
  enabled: true
  auth:
    password: ${REDIS_PASSWORD}
  persistence:
    enabled: true
    size: 5Gi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
