# deployment/k8s/frontend-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wms-frontend
  namespace: workflow-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wms-frontend
  template:
    metadata:
      labels:
        app: wms-frontend
    spec:
      containers:
      - name: frontend
        image: ${ECR_REGISTRY}/wms-frontend:${IMAGE_TAG}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
